- name: Demo on Conditions
  hosts: localhost
  tasks:
    - name: Print Linux
      ansible.builtin.debug:
        msg: Hello Linux
      when: os_name == "Linux"

    - name: Print Unix
      ansible.builtin.debug:
        msg: Hello Unix
      when: os_name == "Unix"